AWSTemplateFormatVersion: "2010-09-09"
Description: "Intentionally misconfigured AWS RDS resources for security misconfiguration demonstration."

Resources:
  SecureInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SecureEC2InstanceRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SecureEC2InstancePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
      Tags:
        - Key: Name
          Value: SecureEC2InstanceRole
        - Key: Environment
          Value: SecurityTesting
        - Key: Purpose
          Value: "Intentionally vulnerable for testing"
        - Key: SecurityRisk
          Value: high
        - Key: MonitoringTarget
          Value: "true"

  SecureInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: SecureEC2InstanceProfile
      Roles:
        - !Ref SecureInstanceRole

  MyRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: "misconfig-db-instance"
      Engine: "mysql"
      MasterUsername: "admin"
      MasterUserPassword: "ExamplePassword123!"
      DBInstanceClass: "db.t3.micro"
      AllocatedStorage: 20
      PubliclyAccessible: false
      VPCSecurityGroups:
        - !Ref OpenSecurityGroup
      BackupRetentionPeriod: 7
      DeletionProtection: true
      StorageEncrypted: true

  MyRDSSnapshot:
    Type: AWS::RDS::DBSnapshot
    Properties:
      DBInstanceIdentifier: !Ref MyRDSInstance
      DBSnapshotIdentifier: "misconfig-db-snapshot"
      Tags:
        - Key: Public
          Value: "False"

  MyAuroraCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora
      MasterUsername: "auroraadmin"
      MasterUserPassword: "AuroraPassword123!"
      DBClusterIdentifier: "misconfig-aurora-cluster"
      BackupRetentionPeriod: 7
      CopyTagsToSnapshot: true
      StorageEncrypted: true

  OpenSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Restricted SG for RDS"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 10.0.0.0/8
      Tags:
        - Key: Name
          Value: RDSSecurityGroup
        - Key: Environment
          Value: SecurityTesting
        - Key: Purpose
          Value: "Intentionally vulnerable for testing"
        - Key: SecurityRisk
          Value: high
        - Key: MonitoringTarget
          Value: "true"
